Remove ambiguous static import of Truth8#assertThat
This caused build errors:

ERROR: BUILD:36:12: Building plugins/high-availability/high-availability_tests-class.jar (54 source files) and running annotation processors (AutoAnnotationProcessor, AutoValueProcessor, AutoOneOfProcessor, AutoValueGsonAdapterFactoryProcessor) failed: (Exit 1): java failed: error executing Javac command (from target //plugins/high-availability:high-availability_tests) external/remotejdk17_macos_aarch64/bin/java '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 19 arguments skipped)
plugins/high-availability/src/test/java/com/ericsson/gerrit/plugins/highavailability/ConfigurationTest.java:181: error: reference to assertThat is ambiguous
    assertThat(getConfiguration().jgroups().protocolStack()).isEmpty();
    ^
  both method assertThat(Optional<?>) in Truth8 and method assertThat(Optional<?>) in Truth match

Change-Id: Ic1619e4aa8e8f3d8ad655717a8e3c59413f0f447