Update patch set 3
Patch Set 3: Verified-1 -Code-Review

This causes the standalone build to fail:

 $ bazel build //...
 .........
 ERROR: /Users/dpursehouse/git/gerrit-plugins/high-availability/tools/eclipse/BUILD:11:1: in classpath_collector rule //tools/eclipse:main_classpath_collect: non-test target '//tools/eclipse:main_classpath_collect' depends on testonly target '//:high-availability__plugin_test_deps' and doesn't have testonly attribute set.
 ERROR: Analysis of target '//tools/eclipse:main_classpath_collect' failed; build aborted.
 INFO: Elapsed time: 9.926s

Patch-set: 3
Reviewer: David Pursehouse <1011123@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1
Label: Code-Review=0