Update patch set 5
Patch Set 5:

tests are not compiling because of errorprone:

src/test/java/com/ericsson/gerrit/plugins/highavailability/cache/CacheEvictionIT.java:70: error: [ThrowIfUncheckedKnownChecked] throwIfUnchecked(knownCheckedException) is a no-op.
                Throwables.throwIfUnchecked(e);
                                           ^
    (see http://errorprone.info/bugpattern/ThrowIfUncheckedKnownChecked)

Patch-set: 5
Reviewer: Gerrit User 1012987 <1012987@173816e5-2b9a-37c3-8a2e-48639d4f1153>